#!/bin/bash

g++ -o prog1 prog1.cpp

for file in testt/test_file_?.txt
do
exec 0< $file
./prog1 >> res.txt
done 

#counting number of the test
count=1

#counting right tests
OK_count=0

for line in $(cat res.txt)
do

#concatinating path to the result files
tmp1="testt/test_res_"
tmp2="$count"
tmp3=".txt"
final="$tmp1$tmp2$tmp3"

if [[ $line == $(cat $final) ]]
then
echo test "$count" is OK
OK_count=$((OK_count + 1))

else 
echo test "$count" is not OK
fi

count=$((count + 1))
done

#deleting temporary file
rm res.txt
echo $'\n' $'\n'
echo OK tests: $OK_count
